### ISSUE TITLE
Investigate using  `callr::rcmd("INSTALL")`

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkginstall#11]

**Comment by jimhester** [comment]
For tarballs, to install them directly instead of the current procedure to build the binary and then install it.

**Comment by gaborcsardi** [comment]
Yeah, it would be `callr::rcmd_bg` I guess or `callr::rcmd_process`.

**Comment by jimhester** [comment]
I guess it really doesn't matter too much in terms of time taken (the package is picked at random, but contains only R code)

``` r
microbenchmark::microbenchmark(times = 5,
pkginstall = system.time(pkginstall::install_source("/tmp/cache/CircMLE_0.2.0.tar.gz")),
rcmd_install = system.time(callr::rcmd("INSTALL", "/tmp/cache/CircMLE_0.2.0.tar.gz")))
#> Unit: milliseconds
#>          expr      min       lq     mean   median       uq      max neval
#>    pkginstall 834.7351 845.0242 924.5079 881.7332 887.9337 1173.114     5
#>  rcmd_install 783.6207 787.2069 809.6070 800.2781 805.7276  871.202     5
```

install_source currently extracts the tarball to a temporary directory, then calls `pkgbuild::build(binary = TRUE)` on it, then `pkginstall::install_binary()` on that.

**Comment by gaborcsardi** [comment]
~~~But `rcmd_process` runs in the background.~~~

Sorry, misunderstood....

**Comment by gaborcsardi** [comment]
I guess `pkgbuild::build` runs the equivalent of `R CMD build` as well. That is not needed, and sometimes might take long. Doesn't that build the vignettes for example?

**Comment by jimhester** [comment]
It runs `R CMD INSTALL --build` if you use the `binary = TRUE` argument.

**Comment by gaborcsardi** [comment]
Interesting. A bit strange, because it does a completely different thing, depending on an argument value. 

Anyway, in that case, it does not really matter. Probably with `callr::rcmd_bg` you get one less R processes.
