### ISSUE TITLE
investigate why you can't just do `R CMD INSTALL .` on a directory

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkginstall#13]

**Comment by gaborcsardi** [comment]
Can't? Why?

**Comment by jimhester** [comment]
I mean you can, and it works fine on most packages, but I am pretty sure there are at least a couple of cases it will fail, I just couldn't remember what they are at the moment.

**Comment by gaborcsardi** [comment]
There is at least `.Rbuildignore` but other things happen as well during `R CMD build`.
