### ISSUE TITLE
How should we handle dependencies in different libraries?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkginstall#14]
E.g. if installing into `lib1` and package `pkg1` is a dependency, and it is not in `lib1`, but it is in `lib2` (in `.libPaths()`), then should we install `pkg1` in `lib1` (as well)?

What if a new version of `pkg1` is required? Leave the old one in `lib2` and put the new one in `lib1`?

Should libraries just be independent completely? I.e. when installing into `lib1` we would ignore `lib2` completely.

**Comment by jimhester** [comment]
I don't think we can ignore them completely, in many cases recommended packages come from a different library than the rest of the packages for instance. Often R + recommended pkgs are installed by sys admins and the users don't have write access to the library. The same situation would happen if the sys admin was installing a linux binary packages.

I agree it would be nice if you could have completely independent libraries, but I don't think it is really feasible in the general case.

For the same reason we can't really necessarily remove old versions from other libraries, I think all we really can assume is the ability to install new packages to the input library and remove existing libraries there.

**Comment by gaborcsardi** [comment]
> For the same reason we can't really necessarily remove old versions from other libraries, I think all we really can assume is the ability to install new packages to the input library and remove existing libraries there.

Agree completely.

>  don't think we can ignore them completely, in many cases recommended packages come from a different library than the rest of the packages for instance. Often R + recommended pkgs are installed by sys admins and the users don't have write access to the library. The same situation would happen if the sys admin was installing a linux binary packages.

Maybe we can handle the packages in the "system" library differently. I.e. we don't even deal with them (by default).

**Comment by gaborcsardi** [comment]
This is not pkginstall's job to decide, so I'll close it.
