### ISSUE TITLE
Optionally add metadata to installed binaries

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkginstall#15]
modify the values in some way ala https://github.com/hadley/devtools/blob/a0c8d7333be185f979a60823dcfad66c9f3ea35e/R/install-remote.R#L75-L102

Also need to invalidate the MD5 if we do this
https://github.com/hadley/devtools/blob/a0c8d7333be185f979a60823dcfad66c9f3ea35e/R/install-remote.R#L106-L116

**Comment by gaborcsardi** [comment]
I am doing this now, because we need it to avoid reinstalling the same (non-cran, non-bioc) packages, over and over again.

**Comment by gaborcsardi** [comment]
@jimhester Sorry, I pushed this to `master` by mistake, can you pls take a look? Thanks!

**Comment by jimhester** [comment]
Thanks, LGTM.
