### ISSUE TITLE
Helper for common build problems

### ISSUE THREAD

**Issue by hadley** [r-lib/pkginstall#18]
i.e. C++11, stringi unicode data

**Comment by gaborcsardi** [comment]
Maybe the best would be to put these in `sysreqsdb` instead of hardcoding them into the package.

**Comment by hadley** [comment]
Yeah, we weren't sure where they should live. I'm imagining we'd only have a handle at most in pkginstall, and otherwise it's worth considering how to implement more generally for any system requirement.

**Comment by jimhester** [comment]
We are going to track this in https://github.com/r-lib/pkgman/issues/15
