### ISSUE TITLE
On windows, move installed package rather than deleting it

### ISSUE THREAD

**Issue by hadley** [r-lib/pkginstall#2]
IIRC I did some experiments a few years ago that suggested it was mostly to move a directory containing a locked DLL, even though you couldn't delete it.

If that fails, we'll need to check to see if the dll is loaded, and fail with an informative before trying to copy.

**Comment by jimhester** [comment]
Ok will try moving it to a new folder in `tempdir()` (to avoid conflicts if there is already a file there)

Maybe we should always do this regardless of OS actually, move the files to tempdir, then try and delete them, then if the delete fails it is not a big deal.

I am using `pkgload::unload()` to unload the package if it is loaded, which should unload the DLL, but I guess there is still an issue if another R process has the package loaded.

**Comment by hadley** [comment]
Yeah, I think that's a good idea.

I'm not sure if we should attempt to unload the package, or just cleanly fail. But if we don't unload, we won't be able to use pkginstall to install pkginstall 😢

**Comment by gaborcsardi** [comment]
And then there are issues when another R process is using it, in which case we can just fail I think. Or ask the user to stop the other session, if `interactive()`.

**Comment by gaborcsardi** [comment]
oh, yeah, @jimhester covered this already...

**Comment by gaborcsardi** [comment]
Btw. I am not sure if we want to `unload()`, considering that a couple of packages cannot be unloaded/reloaded cleanly.

**Comment by hadley** [comment]
Yeah, let's not unload, and consider the problem of using pkginstall to update itself separately.

**Comment by jimhester** [comment]
Ok I will add a fail message which says to use `pkgload::unload(pkgname)` to unload the package.
