### ISSUE TITLE
Remove archive dependency

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkginstall#21]
Who knows if CRAN will ever let archive in, we will have to use R's internal unzip / tar code, or maybe https://github.com/r-lib/zip

**Comment by jimhester** [comment]
Oh wait looks like zip only compresses currently, so I guess `base::unzip()` is what we have to use.

**Comment by gaborcsardi** [comment]
Yeah, I would not add an `unzip` until we have some problems with `base::unzip`.

**Comment by jimhester** [comment]
Well, we do have problems with `base::unzip` right? e.g.

https://github.com/hadley/devtools/issues/1546, https://github.com/hadley/devtools/issues/1464, https://github.com/hadley/devtools/issues/1350

This was most of the reason why I used archive, so we wouldn't have to rely on the base functionality which seems problematic for some people on windows.

**Comment by gaborcsardi** [comment]
Aren't these solved by just forcing the internal unzip? I am sure tbh.

**Comment by gaborcsardi** [comment]
*not* sure

**Comment by gaborcsardi** [comment]
Fixed by #44.
