### ISSUE TITLE
Fix on R 3.1.x

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkginstall#27]
@jimhester do you know why it fails? I can take a look.

**Comment by jimhester** [comment]
I don't know why it is failing, maybe making linux binaries was not supported on 3.1? I can try to reproduce it.

**Comment by gaborcsardi** [comment]
Just asking, because I just fixed `pkgdepends` on 3.1.x, so I have the docker images ready....

**Comment by gaborcsardi** [comment]
NEed to fix `cli` for this, and for that `selectr`: https://github.com/sjp/selectr/issues/8

**Comment by gaborcsardi** [comment]
Fixed by 6d7e4944a0b18f9027eef668fd07e98f072e6dee
