### ISSUE TITLE
Ensure that pkginstall can re-install itself

### ISSUE THREAD

**Issue by hadley** [r-lib/pkginstall#4]
One solution is to avoid loading pkginstall and the package being installed at the same time, at any point of the installation.

**Comment by gaborcsardi** [comment]
pkginstall only has R code, so the only way it can fail while installing itself (or one of its dependencies) is the infamous 
```
lazy-load database x is corrupt
```
error, from here:
https://github.com/wch/r-source/blob/64dfe0255c1d91561862c51efd117d0ed266ea6e/src/main/serialize.c#L3169

I am trying to get a reliable way to reproduce that, and then fix it. The fix just means loading all objets from the lazy-load DB.

**Comment by jimhester** [comment]
I had already fixed that a long time ago in devtools, I think it is in pkgload now. You just need to to force the promises of all objects in the package before you unload it.

**Comment by gaborcsardi** [comment]
Yes, that's what I meant. We are not unloading it here, though. 

Btw. also, we need to force the manual pages as well, that's another lazy load db.
