### ISSUE TITLE
Re-install binary LinkingTo revdeps 

### ISSUE THREAD

**Issue by hadley** [r-lib/pkginstall#8]
And we can't rely on the package version having changed in order to trigger a re-install.

This is bit tricky since presumably CRAN doesn't rebuild old versions of the packages, so you might need to install from source.

(This might not be the package which ends up handling this, but I figured we should record so we don't forget about it)

**Comment by hadley** [comment]
Related packrat code: https://github.com/rstudio/packrat/blob/f970a20b3ee46210b90bdd19bc30019a74c90ab7/R/cache.R#L43-L63

**Comment by gaborcsardi** [comment]
Moved to https://github.com/r-lib/pkgdepends/issues/92
